repos:
-   repo: local
    hooks:
    -   id: pytest
        name: Run pytest (discord-bridge)
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
        args: ["discord-bridge/tests"]
